Add allowed_applications field
shibayan/terraform-azurerm-keyvault-acmebot pull request #65
Opened 2024-03-11 10:58 UTC by jalvarezit

* Add `allowed_applications` so it works with a registered app created independently
* Update deprecated property `object_id` with `application_id`
* Add the posibility to disable function insights

2024-03-11 11:51 UTC, shibayan requested changes
Thank you for your contribution. Thanks for fixing the obsolete properties.

Only the Application Insights on/off feature cannot be allowed. We would like to keep it on in this module as well, as it is essential for identifying errors.

2024-03-11 11:56 UTC, jalvarezit commented
@shibayan I believe that feature is interesting e.g. for qa environments where you do not want to track errors and avoiding that extra cost matters.
Additionally it comes by default enabled so you need to specifically set it to `false` to not include it.

2024-03-11 12:07 UTC, shibayan commented
Tracking errors is for my benefit as well. I cannot sustain development if my support costs increase to save a few cents per month.


Of course you are free to customize your environment, but I would prefer that this be an official module.

2024-03-11 17:28 UTC, jalvarezit commented
@shibayan Do you use Application Insights to send any sort of telemetry in order to solve bugs or is it because you do not want to waste time solving errors without logs enabled making it harder and more time consuming to find a solutio?.

Either case I believe is just better to let the user decide and if they do not have it enabled do not give any bug support at all.

2024-03-11 18:30 UTC, shibayan commented
It doesn't seem reasonable that every time an Issue is created I have to check to see if I have Application Insights enabled each time. The module will not implement the option to enable or disable Application Insights in the future.

2024-03-11 18:33 UTC, closed without merging

2024-03-13 12:46 UTC, jalvarezit commented
@shibayan We can just ignore that feature and merge the other two?